install.packages("mvtnorm")
install.packages("PolynomF")
install.packages("fields")
install.packages("RColorBrewer")
install.packages("png")
install.packages("ggplot2")
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
Sys.setenv(CXXFLAGS = "-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-builtin-macro-redefined -flto -Wno-unused-local-typedefs-Wno-ignored-attributes -Wno-deprecated-declarations")
