install.packages("mvtnorm")
install.packages("PolynomF")
install.packages("fields")
install.packages("RColorBrewer")
install.packages("png")
install.packages("ggplot2")
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
